name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-lcov
        msystem: MINGW64

    - name: Configure CMake
      run: cmake -G "Unix Makefiles" -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build

